name: Test Fabric Notebooks

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test-notebooks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install pyspark pytest
    
    - name: Extract notebook code from Fabric format
      run: |
        echo "📦 Extracting sales_transformations notebook..."
        
        # Copy the Python code from the .Notebook directory
        if [ -f "notebooks/sales_transformations.Notebook/notebook-content.py" ]; then
          cp notebooks/sales_transformations.Notebook/notebook-content.py notebooks/sales_transformations_notebook.py
          echo "✅ Extracted sales_transformations_notebook.py"
        else
          echo "❌ notebook-content.py not found"
          ls -la notebooks/sales_transformations.Notebook/
          exit 1
        fi
        
        # Verify the file
        echo "📄 First 20 lines of extracted code:"
        head -20 notebooks/sales_transformations_notebook.py
    
    - name: Run tests
      run: |
        pytest tests/ -v --tb=short
